administration/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    ########################################################################
    #                                                                      #
    # Create URL's                                                         #
    #                                                                      #
    ########################################################################

    url(r'^employee/create/$', views.CreateEmployeeView.as_view(), name='employee'),
    url(r'^department/create/$', views.CreateDepartmentView.as_view(), name='department'),
    url(r'^customer/create/$', views.CreateCustomerView.as_view(), name='customer'),
    url(r'^test-type/create/$', views.CreateTestTypeView.as_view(), name='test_type'),
    url('^test-request/create/$', views.TestCreateView.as_view(), name='test_request'),

    ########################################################################
    #                                                                      #
    # List (Read) URL's                                                    #
    #                                                                      #
    ########################################################################

    url(r'employees/list/$', views.EmployeeListView.as_view(), name='employee_list'),
    url(r'departments/list/$', views.DepartmentListView.as_view(), name='department_list'),
    url(r'customers/list/$', views.CustomerListView.as_view(), name='customer_list'),
    url(r'test-types/list/$', views.TestTypeListView.as_view(), name='test_type_list'),
    url('^test-requests/list/$', views.TestListView.as_view(), name='test_request_list'),


    ########################################################################
    #                                                                      #
    # Edit (Update) URL's                                                  #
    #                                                                      #
    ########################################################################

    url(r'employee/update/(?P<pk>\d+)/$', views.EmployeeUpdateView.as_view(), name='update_employee'),
    url(r'department/update/(?P<pk>\d+)/$', views.DepartmentUpdateView.as_view(), name='update_department'),
    url(r'customer/update/(?P<pk>\d+)/$', views.CustomerUpdateView.as_view(), name='update_customer'),
    url(r'test-type/update/(?P<pk>\d+)/$', views.TestTypeUpdateView.as_view(), name='update_test_type'),
    url(r'test-request/update/(?P<pk>\d+)/$', views.TestUpdateView.as_view(), name='update_test_request'),

    ########################################################################
    #                                                                      #
    # Delete URL's                                                         #
    #                                                                      #
    ########################################################################

    url(r'employee/delete/(?P<pk>\d+)/$', views.DeleteEmployeeView.as_view(), name='delete_employee'),
    url(r'department/delete/(?P<pk>\d+)/$', views.DeleteDepartmentView.as_view(), name='delete_department'),
    url(r'customer/delete/(?P<pk>\d+)/$', views.DeleteCustomerView.as_view(), name='delete_customer'),
    url(r'test-type/delete/(?P<pk>\d+)/$', views.DeleteTestTypeView.as_view(), name='delete_test_type'),
    url('^test-request/delete/(?P<pk>\d+)/$', views.TestDeleteView.as_view(), name='delete_test_request'),
]

barcode/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^', views.home, name='home')
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.DashboardListView.as_view(), name='dashboard'),
    url(r'^customize-site/', views.CustomizeSettingsTemplateView.as_view(), name='customize'),
    url(r'^administration/', include('administration.urls', namespace='administration')),
    url(r'generate-barcode/', include('barcode.urls', namespace='barcode')),
]

templates/partials/css_dependencies.html
{% load static %}
<!-- Bootstrap core CSS-->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom fonts for this template-->
<link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

<!-- Page level plugin CSS-->
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

templates/partials/footer.html
<footer class="sticky-footer">
    <div class="container">
        <div class="text-center">
            <small>Copyright © Blue Heaven Technologies 2017</small>
        </div>
    </div>
</footer>

templates/partials/icon_cards.html
<!-- ICON CARDS -->
<div class="row">
    <!-- New Messages Card -->
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-primary o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fa fa-fw fa-comments"></i>
                </div>
                <div class="mr-5">26 New Messages!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right"><i class="fa fa-angle-right"></i></span>
            </a>
        </div>  <!-- ./card -->
    </div>  <!-- /.col -->

    <!-- New Tasks Card -->
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-warning o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fa fa-fw fa-list"></i>
                </div>
                <div class="mr-5">11 New Tasks!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right"><i class="fa fa-angle-right"></i></span>
            </a>
        </div>  <!-- /.card -->
    </div>  <!-- /.col -->

    <!-- New Orders Card -->
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-success o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fa fa-fw fa-shopping-cart"></i>
                </div>
                <div class="mr-5">123 New Orders!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right"><i class="fa fa-angle-right"></i></span>
            </a>
        </div>  <!-- /.card -->
    </div>  <!-- /.col -->

    <!-- New Tickets Card -->
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-danger o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fa fa-fw fa-support"></i>
                </div>
                <div class="mr-5">13 New Tickets!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right"><i class="fa fa-angle-right"></i></span>
            </a>
        </div>  <!-- /.card -->
    </div>  <!-- /.col -->
</div>    <!-- /.row -->

templates/partials/javascript_dependencies.html
{% load static %}
<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin.min.js' %}"></script>

<!-- Custom scripts for this page-->
<script src="{% static 'js/sb-admin-datatables.min.js' %}"></script>

templates/partials/logout_modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>  <!-- /.modal-header -->
            <div class="modal-body">Select "Logout" below if you are ready to end your current session. (Not implemented yet.)</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="#">Logout</a>
            </div>  <!-- /.modal-footer -->
        </div>  <!-- /.modal-content -->
    </div>  <!-- /.modal-dialog -->
</div>  <!-- /.modal -->

templates/partials/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <!-- Navbar Logo -->
    <a class="navbar-brand" href="{% url 'dashboard' %}">Blue Heaven Technologies</a>

    <!-- Hamburger Control -->
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navigation Menus -->
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <!-- Side Navigation -->
        {% include 'partials/sidebar_navigation.html' %}

        <!-- Top Navigation -->
        {% include 'partials/topbar_navigation.html' %}
    </div>
</nav>

templates/partials/sidebar_navigation.html
<ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
    <!-- Dashboard Link -->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
        <a class="nav-link" href="{% url 'dashboard' %}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
        </a>
    </li>

    <!-- Test Request Link -->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Test Request">
        <a class="nav-link" href="{% url 'administration:test_request' %}">
            <i class="fa fa-fw fa-shopping-cart"></i>
            <span class="nav-link-text">New Test Request</span>
        </a>
    </li>

    <!--&lt;!&ndash; Barcode Link &ndash;&gt;-->
    <!--<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Barcode">-->
        <!--<a class="nav-link" href="{% url 'barcode:home' %}">-->
            <!--<i class="fa fa-fw fa-qrcode"></i>-->
            <!--<span class="nav-link-text">Generate Barcode</span>-->
        <!--</a>-->
    <!--</li>-->

    <!--&lt;!&ndash; Filter Queue Link &ndash;&gt;-->
    <!--<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Filter Queue">-->
        <!--<a class="nav-link" href="#">-->
            <!--<i class="fa fa-fw fa-hourglass-start"></i>-->
            <!--<span class="nav-link-text">Filter Queue</span>-->
        <!--</a>-->
    <!--</li>-->

    <!-- Lists Links -->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Lists">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseLists" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">Lists</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseLists">
            <li><a href="{% url 'administration:customer_list' %}">Customers</a></li>
            <li><a href="{% url 'administration:test_type_list' %}">Test Types</a></li>
            <li><a href="{% url 'administration:department_list' %}">Departments</a></li>
            <li><a href="{% url 'administration:employee_list' %}">Employees</a></li>
        </ul>
    </li>

    <!-- Administration Links -->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Administration">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseAdministration" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-lock"></i>
            <span class="nav-link-text">Administration</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseAdministration">
            <li><a href="{% url 'administration:customer' %}">Create Customer</a></li>
            <li><a href="{% url 'administration:test_type' %}">Create Test Type</a></li>
            <li><a href="{% url 'administration:department' %}">Create Department</a></li>
            <li><a href="{% url 'administration:employee' %}">Create Employee</a></li>
        </ul>
    </li>

    <!-- External Links -->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="External Links">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExternalLinks" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-link"></i>
            <span class="nav-link-text">External Links</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseExternalLinks">
            <li><a href="http://bht-docs.local:8080" target="_blank">Document Library</a></li>
            <li><a href="http://bht-servicedesk.local:8080" target="_blank">Help Desk</a></li>
            <li><a href="http://www.blueheaventech.com" target="_blank">Website</a></li>
            <li><a href="https://outlook.office.com/owa" target="_blank">Outlook</a></li>
            <li><a href="https://bht-cloud.local/" target="_blank">Cloud</a></li>
        </ul>
    </li>

    <!--&lt;!&ndash; Customize Settings &ndash;&gt;-->
    <!--<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">-->
        <!--<a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">-->
            <!--<i class="fa fa-fw fa-wrench"></i>-->
            <!--<span class="nav-link-text">Customization Settings</span>-->
        <!--</a>-->
        <!--<ul class="sidenav-second-level collapse" id="collapseComponents">-->
            <!--<li><a href="{% url 'customize' %}">Navbar</a></li>-->
            <!--<li><a href="#">Cards</a></li>-->
        <!--</ul>-->
    <!--</li>-->
</ul>

<!-- Navigation Expand/Collapse Button -->
<ul class="navbar-nav sidenav-toggler">
    <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler"><i class="fa fa-fw fa-angle-left"></i></a>
    </li>
</ul>

templates/partials/topbar_navigation.html
<ul class="navbar-nav ml-auto">
    <!-- Logout Button -->
    <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout
        </a>
    </li>
</ul>