administration/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    ########################################################################
    #                                                                      #
    # Create URL's                                                         #
    #                                                                      #
    ########################################################################

    url(r'^employee/create/$', views.CreateEmployeeView.as_view(), name='employee'),
    url(r'^department/create/$', views.CreateDepartmentView.as_view(), name='department'),
    url(r'^customer/create/$', views.CreateCustomerView.as_view(), name='customer'),
    url(r'^test-type/create/$', views.CreateTestTypeView.as_view(), name='test_type'),
    url('^test-request/create/$', views.TestCreateView.as_view(), name='test_request'),

    ########################################################################
    #                                                                      #
    # List (Read) URL's                                                    #
    #                                                                      #
    ########################################################################

    url(r'employees/list/$', views.EmployeeListView.as_view(), name='employee_list'),
    url(r'departments/list/$', views.DepartmentListView.as_view(), name='department_list'),
    url(r'customers/list/$', views.CustomerListView.as_view(), name='customer_list'),
    url(r'test-types/list/$', views.TestTypeListView.as_view(), name='test_type_list'),
    url('^test-requests/list/$', views.TestListView.as_view(), name='test_request_list'),


    ########################################################################
    #                                                                      #
    # Edit (Update) URL's                                                  #
    #                                                                      #
    ########################################################################

    url(r'employee/update/(?P<pk>\d+)/$', views.EmployeeUpdateView.as_view(), name='update_employee'),
    url(r'department/update/(?P<pk>\d+)/$', views.DepartmentUpdateView.as_view(), name='update_department'),
    url(r'customer/update/(?P<pk>\d+)/$', views.CustomerUpdateView.as_view(), name='update_customer'),
    url(r'test-type/update/(?P<pk>\d+)/$', views.TestTypeUpdateView.as_view(), name='update_test_type'),
    url(r'test-request/update/(?P<pk>\d+)/$', views.TestUpdateView.as_view(), name='update_test_request'),

    ########################################################################
    #                                                                      #
    # Delete URL's                                                         #
    #                                                                      #
    ########################################################################

    url(r'employee/delete/(?P<pk>\d+)/$', views.DeleteEmployeeView.as_view(), name='delete_employee'),
    url(r'department/delete/(?P<pk>\d+)/$', views.DeleteDepartmentView.as_view(), name='delete_department'),
    url(r'customer/delete/(?P<pk>\d+)/$', views.DeleteCustomerView.as_view(), name='delete_customer'),
    url(r'test-type/delete/(?P<pk>\d+)/$', views.DeleteTestTypeView.as_view(), name='delete_test_type'),
    url('^test-request/delete/(?P<pk>\d+)/$', views.TestDeleteView.as_view(), name='delete_test_request'),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.DashboardListView.as_view(), name='dashboard'),
    url(r'^customize-site/', views.CustomizeSettingsTemplateView.as_view(), name='customize'),
    url(r'^administration/', include('administration.urls', namespace='administration')),
    url(r'generate-barcode/', include('barcode.urls', namespace='barcode')),
]

administration/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from django_tables2 import RequestConfig

from . import models
from . import tables
from . import mixins


########################################################################
#                                                                      #
# Create Views                                                         #
#                                                                      #
########################################################################


class CreateEmployeeView(LoginRequiredMixin, mixins.PageTitleMixin, CreateView):
    model = models.Employee
    page_title = "Employee"
    template_name = 'administration/create_update_template.html'
    fields = (
        'first_name',
        'last_name',
        'email',
        'phone',
        'department',
    )


class CreateDepartmentView(LoginRequiredMixin, mixins.PageTitleMixin, CreateView):
    model = models.Department
    page_title = "Department"
    template_name = 'administration/create_update_template.html'
    fields = (
        'name',
        'manager',
    )


class CreateCustomerView(LoginRequiredMixin, mixins.PageTitleMixin, CreateView):
    model = models.Customer
    page_title = "Customer"
    template_name = 'administration/create_update_template.html'
    fields = (
        'company',
        'first_name',
        'last_name',
        'email',
        'address',
        'phone',
    )


class CreateTestTypeView(LoginRequiredMixin, mixins.PageTitleMixin, CreateView):
    model = models.TestType
    page_title = "Test Type"
    template_name = 'administration/create_update_template.html'
    fields = (
        'name',
        'code',
        'price',
        'department',
    )


class TestCreateView(CreateView):
    model = models.Test
    template_name = 'administration/requests_create_update_template.html'
    fields = (
        'customer',
        'test_type',
        'air_flow_rate',
        'quote_number',
        'po_number',
        'manufacturer',
        'model_number',
        'part_number',
        'filter_type',
        'date_code',
        'nominal_height',
        'nominal_width',
        'nominal_depth',
        'pleat_quantity',
        'pocket_quantity',
        'media_type',
        'adhesive_type',
        'adhesive_amount',
        'disposal',
        'test_dust',
        'final_resistance',
        'dust_feed_rate',
        'initial_loading_pressure',
        'hi_pulse_pressure',
        'lo_pulse_pressure',
        'pulse_ms_on',
        'pulse_ms_off',
        'pulse_pressure',
        'not_to_exceed_pressure',
        'location',
    )

    def get_context_data(self, **kwargs):
        context = super(TestCreateView, self).get_context_data(**kwargs)
        model_name = models.Test.__name__
        context['model_name'] = model_name
        return context


########################################################################
#                                                                      #
# List (Read) Views                                                    #
#                                                                      #
########################################################################


class EmployeeListView(mixins.PageTitleMixin, ListView):
    model = models.Employee
    page_title = "Employees"
    template_name = 'administration/list_view_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        table = tables.EmployeeTable(models.Employee.objects.all())
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        context['table'] = table
        return context


class DepartmentListView(mixins.PageTitleMixin, ListView):
    model = models.Department
    page_title = "Departments"
    template_name = 'administration/list_view_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        table = tables.DepartmentTable(models.Department.objects.all())
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        context['table'] = table
        return context


class CustomerListView(mixins.PageTitleMixin, ListView):
    model = models.Customer
    page_title = "Customers"
    template_name = 'administration/list_view_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        table = tables.CustomerTable(models.Customer.objects.all())
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        context['table'] = table
        return context


class TestTypeListView(mixins.PageTitleMixin, ListView):
    model = models.TestType
    page_title = "Test Types"
    template_name = 'administration/list_view_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        table = tables.TestTypeTable(models.TestType.objects.all())
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        context['table'] = table
        return context


class TestListView(ListView):
    model = models.Test
    template_name = 'administration/requests_list_view_template.html'

    def get_context_data(self, **kwargs):
        context = super(TestListView, self).get_context_data(**kwargs)
        table = tables.TestRequestsTable(models.Test.objects.all())
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        context['table'] = table
        return context


########################################################################
#                                                                      #
# Update Views                                                         #
#                                                                      #
########################################################################


class EmployeeUpdateView(LoginRequiredMixin, mixins.PageTitleMixin, UpdateView):
    model = models.Employee
    page_title = "Employee"
    template_name = 'administration/create_update_template.html'
    fields = (
        'first_name',
        'last_name',
        'email',
        'phone',
        'department',
    )


class DepartmentUpdateView(LoginRequiredMixin, mixins.PageTitleMixin, UpdateView):
    model = models.Department
    page_title = "Department"
    template_name = 'administration/create_update_template.html'
    fields = (
        'name',
        'manager',
    )


class CustomerUpdateView(LoginRequiredMixin, mixins.PageTitleMixin, UpdateView):
    model = models.Customer
    page_title = "Customer"
    template_name = 'administration/create_update_template.html'
    fields = (
        'company',
        'first_name',
        'last_name',
        'email',
        'address',
        'phone',
    )


class TestTypeUpdateView(LoginRequiredMixin, mixins.PageTitleMixin, UpdateView):
    model = models.TestType
    page_title = "Test Type"
    template_name = 'administration/create_update_template.html'
    fields = (
        'name',
        'code',
        'price',
        'department',
    )


class TestUpdateView(UpdateView):
    model = models.Test
    template_name = 'administration/requests_create_update_template.html'
    fields = (
        'customer',
        'test_type',
        'air_flow_rate',
        'quote_number',
        'po_number',
        'manufacturer',
        'model_number',
        'part_number',
        'filter_type',
        'date_code',
        'nominal_height',
        'nominal_width',
        'nominal_depth',
        'pleat_quantity',
        'pocket_quantity',
        'media_type',
        'adhesive_type',
        'adhesive_amount',
        'disposal',
        'test_dust',
        'final_resistance',
        'dust_feed_rate',
        'initial_loading_pressure',
        'hi_pulse_pressure',
        'lo_pulse_pressure',
        'pulse_ms_on',
        'pulse_ms_off',
        'pulse_pressure',
        'not_to_exceed_pressure',
        'location',
        'barcode_number',
    )

    def get_context_data(self, **kwargs):
        context = super(TestUpdateView, self).get_context_data(**kwargs)
        model_name = models.Test.__name__
        context['model_name'] = model_name
        return context


########################################################################
#                                                                      #
# Delete Views                                                         #
#                                                                      #
########################################################################


class DeleteEmployeeView(LoginRequiredMixin, mixins.PageTitleMixin, DeleteView):
    model = models.Employee
    page_title = "Employee"
    template_name = 'administration/confirm_delete_template.html'
    success_url = reverse_lazy('administration:employee_list')


class DeleteDepartmentView(LoginRequiredMixin, mixins.PageTitleMixin, DeleteView):
    model = models.Department
    page_title = "Department"
    template_name = 'administration/confirm_delete_template.html'
    success_url = reverse_lazy('administration:department_list')


class DeleteCustomerView(LoginRequiredMixin, mixins.PageTitleMixin, DeleteView):
    model = models.Customer
    page_title = "Customer"
    template_name = 'administration/confirm_delete_template.html'
    success_url = reverse_lazy('administration:customer_list')


class DeleteTestTypeView(LoginRequiredMixin, mixins.PageTitleMixin, DeleteView):
    model = models.TestType
    page_title = "Test Type"
    template_name = 'administration/confirm_delete_template.html'
    success_url = reverse_lazy('administration:test_type_list')


class TestDeleteView(DeleteView):
    model = models.Test

administration/templates/administration/confirm_delete_template.html
{% extends 'base.html' %}
{% load administration_extras %}

{% block page_title %}Delete {{ page_title }} {% endblock %}

{% block content %}
<div class="container">
    <form class="form" method="POST">
        {% csrf_token %}
        <p>This action will delete the {{ page_title|lower }} from the database. This cannot be undone.</p>
        <p><b>Are you sure you want to proceed?</b></p>
        <input type="submit" class="btn btn-danger" value="Yes">
        {% if page_title|lower == 'employee' %}
            <a href="{% url 'administration:employee_list' %}" class="btn btn-info">No</a>
        {% elif page_title|lower == 'department' %}
            <a href="{% url 'administration:department_list' %}" class="btn btn-info">Cancel</a>
        {% elif page_title|lower == 'customer' %}
            <a href="{% url 'administration:customer_list' %}" class="btn btn-info">Cancel</a>
        {% elif page_title|lower == 'test type' %}
            <a href="{% url 'administration:test_type_list' %}" class="btn btn-info">Cancel</a>
        {% endif %}
    </form>
</div>
{% endblock %}

administration/templates/administration/create_update_template.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load administration_extras %}

{% block title %} {% if not form.instance.pk %} Create {% else %} Update {% endif %} {{ page_title }} {% endblock %}

{% block page_title %} {% if not form.instance.pk %} Create {% else %} Update {% endif %} {{ page_title }} {% endblock %}

{% block content %}
<div class="container">
    <form class="form" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        {% if form.instance.pk %}
            <div class="text-left">
                <input type="submit" value="Update" class="btn btn-warning">
                {% if page_title|lower == 'employee' %}
                    <a href="{% url 'administration:delete_employee' pk=form.instance.pk %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'administration:employee_list' %}" class="btn btn-info">Cancel</a>
                {% elif page_title|lower == 'department' %}
                    <a href="{% url 'administration:delete_department' pk=form.instance.pk %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'administration:department_list' %}" class="btn btn-info">Cancel</a>
                {% elif page_title|lower == 'customer' %}
                    <a href="{% url 'administration:delete_customer' pk=form.instance.pk %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'administration:customer_list' %}" class="btn btn-info">Cancel</a>
                {% elif page_title|lower == 'test type' %}
                    <a href="{% url 'administration:delete_test_type' pk=form.instance.pk %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'administration:test_type_list' %}" class="btn btn-info">Cancel</a>
                {% endif %}
            </div>
        {% else %}
            <div class="text-left">
                <input type="submit" value="Save" class="btn btn-success">
            </div>
        {% endif %}
    </form>
</div>
{% endblock %}

administration/templates/administration/list_view_template.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load administration_extras %}
{% load static %}

{% block title %} {{ page_title }} {% endblock %}

{% block page_title %} {{ page_title }} {% endblock %}

{% block content %}
<div class="container">
    <div class="table-responsive">
        {% render_table table %}
    </div>  <!-- /.table-responsive -->
</div>  <!-- /.container -->
{% endblock %}

administration/templates/administration/requests_confirm_delete_template.html
{% extends 'base.html' %}
{% load administration_extras %}

{% block title %}Delete {{ test.pk|format_job_number }} {% endblock %}

{% block page_title %}Delete {{ test.pk|format_job_number }} {% endblock %}

{% block content %}
<div class="container">
    <form class="form" method="POST" action="">
        {% csrf_token %}
        <p>This action will delete {{ test.pk|format_job_number }} from the database. This cannot be undone. </p>
        <p><b>Are you sure you want to delete {{ test.pk|format_job_number }}?</b></p>
        <input type="submit" class="btn btn-danger" value="Yes"><a href="{% url 'administration:test_request_list' %}" class="btn btn-info">No</a>
    </form>
</div>
{% endblock %}

administration/templates/administration/requests_create_update_template.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load administration_extras %}

{% block title %}{% if not form.instance.pk %}Create Test Request{% else %}Update {{ form.instance.pk|format_job_number }}{% endif %}{% endblock %}

{% block page_title %}{% if not form.instance.pk %}Create Test Request{% else %}Update {{ form.instance.pk|format_job_number }}{% endif %}{% endblock %}

{% block content %}
<div class="container">
    <form class="form" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        {% if form.instance.pk %}
            <input type="submit" value="Update" class="btn btn-warning">
            <a href="{% url 'administration:delete_test_request' pk=form.instance.pk %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'administration:test_request_list' %}" class="btn btn-info">Cancel</a>
        {% else %}
            <input type="submit" value="Save" class="btn btn-success">
        {% endif %}
    </form>
</div>
{% endblock %}

administration/templates/administration/requests_list_view_template.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load static %}

{% block title %}2018 Job List{% endblock %}

{% block page_title %}2018 Job List{% endblock %}

{% block content %}
<div class="container">
    <div class="table-responsive">
        {% render_table table %}
    </div>  <!-- /.table-responsive -->
</div>  <!-- /.container -->
{% endblock %}